[Interface]
PrivateKey = yPpL+0lvqJDN7RWIE/jCDVRRdVtxN43o0gauTTWExl0=
Address    = 10.0.0.1/24
ListenPort = 51820

[laptop-1]
PublicKey  = a7ZRIYNxsa35n57QoqKCH2v0MzmAGzo7QHG/XMlX5Go=
PrivateKey = yJqYz/QYHKYNCMSvvvrhqfreAOkVnMVBBGMlGliU5XE=
AllowedIPs = 10.0.0.3/32
